services:

  php:
    build: php
    ports:
      - 8080:8080
    volumes:
      - ../site:/FirstApp
    working_dir: /FirstApp
    entrypoint: [ php, -S, 0.0.0.0:8080 ]
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_1
      MYSQL_USER: task_1
      MYSQL_PASSWORD: task_1
      MYSQL_RANDOM_ROOT_PASSWORD: false
    ports:
      - 3306:3306